// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Shared-repo",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//          {children}
//       </body>
//     </html>
//   );
// }




import { Providers } from '@/lib/Providers';
import Navbar from '../components/layout/Navbar';
import './globals.css';
import { Toaster } from 'react-hot-toast';

export const metadata = {
  title: 'My Reusable App',
  description: 'A reusable Next.js app with authentication and CRUD',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Navbar />
          <main className="max-w-7xl mx-auto p-4">{children}</main>
          <Toaster position="top-right" />
        </Providers>
      </body>
    </html>
  );
}